version     = "0.1.0"
author      = "Softmax"
description = "THE CABINET: four arcade cabinets ring a square CRT, each defending a gap in its own wall with a paddle that is also a gun."
license     = "MIT"

srcDir = "src"

requires "nim >= 2.2.4"
requires "bitworld >= 0.1.0"
requires "pixie"
requires "mummy >= 0.4.7"
requires "curly >= 1.1.1"
requires "whisky >= 0.1.3"
requires "supersnappy >= 2.1.3"
requires "jsony"
requires "zippy"
requires "flatty >= 0.3.4"
