## Regenerates tests/data/golden_hashes.json — the committed hash fixture the
## determinism gate pins. Run it ONLY when the rules deliberately change, in
## the same commit as the GameVersion bump.
##
##   nim r --path:src --path:tests tools/gen_golden_hashes.nim

import std/[json, os]
import cabinet/sim
import helpers

const
  Seed = 5140913
  StartingLives = 3
  MaxTicks = 1440
  Every = 48

when isMainModule:
  var roms = newJObject()
  for rom in ["warlords", "quadrapong", "foozpong"]:
    let config = episodeConfig(
      Seed, rom = rom, startingLives = StartingLives, maxTicks = MaxTicks)
    let episode = runEpisode(config)
    var hashes = newJArray()
    var tick = Every
    while tick <= episode.hashes.len:
      hashes.add(%[%tick, %int64(cast[int64](episode.hashes[tick - 1]))])
      tick += Every
    roms[rom] = %*{"ticks": episode.ticks, "hashes": hashes}
    echo rom, ": ", episode.ticks, " ticks, ", hashes.len, " pinned hashes"
  let document = %*{
    "note": "Generated by tools/gen_golden_hashes.nim. The determinism gate " &
      "(tests/test_determinism.nim) pins every 48th tick of a four-bulwark " &
      "episode in each ROM. If this file has to change, the RULES changed: " &
      "bump GameVersion in the same commit.",
    "gameVersion": GameVersion,
    "seed": Seed,
    "startingLives": StartingLives,
    "maxTicks": MaxTicks,
    "every": Every,
    "roms": roms
  }
  writeFile("tests/data/golden_hashes.json", document.pretty() & "\n")
  echo "wrote tests/data/golden_hashes.json"
